let Pseudo = "AyoubX"
let Niveau = "19"
let Age = "23"
let Score = "9996"
let Pays = "Maroc"
console.log("Pseudo : ", Pseudo);
console.log("Niveau : ", Niveau);
console.log("Age : ", Age);
console.log("Score : ", Score);
console.log("Pays : ", Pays);